### PR TITLE
store folder name to layer

### PR DESCRIPTION
**Pull request by skydiablo**

### CODE REVIEW

**Comment by mdorda** [comment]
Why do you need that? What does it fix?

**Comment by skydiablo** [comment]
that allow me to add a kml with an layer-control with layer-name. by now, kml-folder-names are missing. or i'm wrong?

**Comment by skydiablo** [comment]
like this:

        fetch('URL')
            .then(res => res.text())
            .then(kmltext => {
                // Create new kml overlay
                const parser = new DOMParser();
                const kml = parser.parseFromString(kmltext, 'text/xml');
                const layers = new L.KML(kml);
                map.on('layeradd', eventLayerAdd);
                map.addLayer(layers);
            });

        const eventLayerAdd = function (e) {
            if (e.layer.options) {
                let name = e.layer.options.name;
                if (name) {
                    if (!layerControl._getLayer(L.stamp(e.layer))) { //already added ?
                        layerControl.addOverlay(e.layer, name);
                    }
                }
            }
        }

**Comment by mdorda** [comment]
Ok, it makes sense. Thank you for the details. And the result from `L.stamp` cannot be used instead of the `name`?

**Comment by skydiablo** [comment]
the result from `L.stamp` is just a number, how do you want to get the name?

**Comment by mdorda** [comment]
I mean, if you need just an identificator, `L.stamp` may work. But if you need (for some reason) name and nothing more than name, your merge request makes sense.

**Comment by skydiablo** [comment]
on the other hand, is there any (for me unknown) workflow to get the folder-name from the KML?

**Comment by skydiablo** [comment]
thx, in the near future, we should recheck this feature. so many other objects have an `name` tag. see [reference](https://developers.google.com/kml/documentation/kmlreference#-feature-), like:

- Placemark
- Folder
- NetworkLink

so we can abstract this lines into a higher order to handle all of this objects...

**Pull request merged**
